### ISSUE TITLE
Works but post processing affects the full window? - Is there a way to solve this?

### ISSUE THREAD

**Issue by twhittyham** [sator-imaging/AppWindowUtility#1]
I have it working using HDRP, but when the window is transparent the post processing affects the background so it not fully transparent.
Is there a possible way to solve it?
Regards
T

![image](https://user-images.githubusercontent.com/106953031/172114797-80be2886-f086-4a05-86e1-955666c77dfc.png)

**Comment by sator-imaging** [comment]
Hi @twhittyham,

It seems that this could caused by Scene Fog or other volumetric effects.
make sure that background is completely clear, no colors and alphas.
