### ISSUE TITLE
Sample scripts available? Error message when trying to call code: "'AppWindowUtility' in explicit interface declaration is not an interface"

### ISSUE THREAD

**Issue by emotion-engineer** [sator-imaging/AppWindowUtility#3]
Is there a sample script or scene somewhere? This is exactly what I need but it's a little over my head and I'm not sure how to implement the code. I'm just trying to make a transparent, resizable window with normal borders and a handle up top. When trying to reference 'AppWindowUtility' I keep getting the error "'AppWindowUtility' in explicit interface declaration is not an interface":

![image](https://user-images.githubusercontent.com/110819505/190529226-c28d9393-0f42-4601-9618-6de2d5c71717.png)

I'd like to build something like in the [gif here](https://github.com/sator-imaging/sator-imaging.github.io/raw/master/AppWindowUtility/images/Opacity.gif?raw=true) but I need to see how the code is laid out. Can I find a script like that anywhere?

**Comment by sator-imaging** [comment]
Would you like to tell me what Unity version you use?

**Comment by eschewary** [comment]
2021.2.6f1

**Comment by eschewary** [comment]
> Would you tell me what Unity version you use?

2021.2.6f1

**Comment by eschewary** [comment]
@sator-imaging Have you seen this error before? I've included 'using SatorImaging.AppWindowUtility;', I don't have anything else in the script and the error pops up. How can I call the code? Can I see an example scene and component so I can see how it's supposed to be set up? 


![image](https://user-images.githubusercontent.com/110819505/191139138-1c7fec31-59c4-419e-90e9-4a774e12897c.png)

**Comment by sator-imaging** [comment]
@eschewary 

Almostly achieved! try this.

```csharp
using UnityEngine;
using SatorImaging.AppWindowUtility;

public class MyTest : MonoBehaviour
{
    void Start()
    {
        AppWindowUtility.Transparent = true;
    }
}
```

**Comment by eschewary** [comment]
@sator-imaging That's it! Thank you so much, I've been at this for a year haha this is amazing work. Do you have a tip or donate link? Also, I'm trying to get 'Transparent = true' and then 'FrameVisibility = true' as you suggest to remove background filling from application window, but it's not working, my window is not transparent if both are set to 'true'.  How do I include checkboxes like you have inside the window? Do you have a sample script of that object in the gif?

**Comment by eschewary** [comment]
Here's an example of the frame color filling the window
![transparent_frame_issue](https://user-images.githubusercontent.com/110819505/191404171-c0185ce3-3704-4878-97b8-86c8267fc624.gif)

**Comment by emotion-engineer** [comment]
@sator-imaging Are you able to achieve a transparent background with the frame borders on, as the documentation suggests? If not I will create a separate issue and make a code bounty for it.

**Comment by emotion-engineer** [comment]
Ok thank you. It would be nice to have that built in to this, do you have suggestions for a code bounty for ? Also click-through is not working for me. Is this a known issue?

**Comment by emotion-engineer** [comment]
@sator-imaging Thank you, I got it working. I am still seeing extreme mouse slowdown when I'm using a transparent app. Is there a solution here?

Also I'd like to support your work, do you have a donation link?

**Comment by emotion-engineer** [comment]
> @sator-imaging *Sorry, I seem to have fixed the mouse slowdown issue , or I'm not able to recreate it atm. I would still like to donate to you or your work! Drop a link if you see fit. Thank you again for your project!
